### ISSUE TITLE
Support for RabbitMQ 3.x 

### ISSUE THREAD

**Issue by jkodumal** [sstone/amqp-client#20]
I'm seeing the following error from my test application using amqp-client 1.1 with RabbitMQ 3.x:

```
com.rabbitmq.client.ShutdownSignalException: connection error; reason: {#method<connection.close>(reply-code=540, reply-text=NOT_IMPLEMENTED - immediate=true, class-id=60, method-id=40), null, ""}
```

Some googling about revealed [this document](http://www.rabbitmq.com/blog/2012/11/19/breaking-things-with-rabbitmq-3-0/), which mentions that support for the 'immediate' flag has been removed in 3.x.

Downgrading to RabbitMQ 2.8.x resolves the problem.

**Comment by sstone** [comment]
Hi,

The client works with RabbitMQ 3.x (we use it in production), you just need to set the immediate flag to false. I was aware of this change but kept the 'immediate' flag because it is still part of the RabbitMQ java client (okay they have 2 publish methods, one with 'immediate' and one without...) and because it might also be used with another AMQP 0.9.1 broker (though I think Rabbit is the only active option). I'm now inclined to remove 'immediate' and add another constructor for Publish with an 'immediate' parameter that is discarded.

Are you stuck with this i.e do you already have an application that relies on 'immediate' and that you want to use with Rabbit 3.X ?

Thanks!

**Comment by jkodumal** [comment]
It's not a problem as my app doesn't rely on `immediate`. I could have sworn I tried setting `immediate` to `false`, but clearly I didn't. Thanks for the help!

**Comment by sstone** [comment]
You're welcome!
