### ISSUE TITLE
Consumer stalls with qos set - 1.3

### ISSUE THREAD

**Issue by bearrito** [sstone/amqp-client#60]
If I set the QoS to N, my system seems to never acknowledge the messages.

https://gist.github.com/bearrito/b65037085989e18ff38c

Given the code in the Gist, I will see log messages that indicate the messages have been acked, but I don't receive anymore messages and the RabbitMQ admin console shows two unacked messages.

**Comment by sstone** [comment]
Hi,

Sorry for not replying earlier, I'm pretty busy on my new project. 
There are a few projects in production that rely on qos (for load balancing and throughput management) and it really seems to work.
I've put up a simple test there: https://gist.github.com/sstone/fe77b0e838060a55fe68
it works as expected and you can play with the duration and qos to see how it affects its behaviour.

If there is a steady flow of incoming messages, then the admin console will always show "N unacked messages".

Could you please either modify the gist above are add the missing parts to yours so that I have a complete sample to test with ?

Thanks! (and sorry if I've missed something)
